# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_roll_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
