# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-06 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190806_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_roll_number',
            field=models.IntegerField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
